### ISSUE TITLE
CLI-Argument for output path - relative paths should be resolved using the current working directory

### ISSUE THREAD

**Issue by lord-haffi** [Hochfrequenz/bo4e-dotnet-generator.py#7]
Output-Pfade sollte man besser vom User definieren lassen, d.h. als CLI Argument setzen. Hier können dann relative Pfade mit dem cwd aufgelöst werden.

**Comment by hamidhajiparvaneh** [comment]
https://github.com/Hochfrequenz/bo4e-dotnet-generator.py/pull/23 done
