### ISSUE TITLE
Separate BO4E-Schema-Tool from code generation - Remove dependency

### ISSUE THREAD

**Issue by lord-haffi** [Hochfrequenz/bo4e-dotnet-generator.py#8]
Eigentlich ist es so gedacht (und sinnvoller imo), dass die Tools getrennt bleiben, d.h. dass das BO4E-Schema-Tool nicht vom C#-Generator ausgeführt wird und dementsprechend auch gar nicht erst eine Dependency ist. Man würde die Tools dann einfach nacheinander ausführen. Sonst müsstest du immer alle Argumente von bost auch als Argumente von dem neuen CLI definieren, sonst verlierst du Funktionalität.

**Comment by hamidhajiparvaneh** [comment]
https://github.com/Hochfrequenz/bo4e-dotnet-generator.py/pull/25
